version: "3.8"
services:
   mysqldb:
      image: mysql:8.0
      env_file: ./.env
      environment:
         - MYSQL_DATABASE=$NODE_DB_NAME
         - MYSQL_USER=$NODE_DB_USER_ROOT
         - MYSQL_PASSWORD=$NODE_DB_PASS_ROOT
         - MYSQL_ROOT_PASSWORD=$NODE_DB_PASS_ROOT
   web:
      build: .
      command: npm run start
      volumes:
         - .:/app/
         - /app/node_modules
      ports:
         - "5010:5010"

      depends_on:
         - mysqldb
